version: "3.5"
services:
  centos7msgpackphp5:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.php-5
  centos6msgpackphp5:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.php-5
      args:
        centos: 6

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
